clear scr;
select * from users;
select * from teachers;
select * from students;
select * from batch_info;
select * from batch_record;
select * from subject_info;
select * from class_info;
select * from class_record;
select * from atd_info;
select * from atd_log;